### ISSUE TITLE
这个demo有些MP3

### ISSUE THREAD

**Issue by PingStudyCode** [T-chuangxin/VideoMergeDemo#1]
大神，CheapMP3.java中的读写算法看不明白，能否解释下或者提供一些资料，谢谢

**Comment by T-chuangxin** [comment]
？

**Comment by PingStudyCode** [comment]
您好，我参考您的CheapMp3算法对mp3文件进行裁剪，实际操作中发现有一些mp3文件会出现剪切失败的情况，剪切失败有两种情况：1、剪切完的文件只有几十kB，只能播放1-2s，而且是杂音，2、无法执行剪切，而这一类MP3文件有一个共性就是解析预览出来的波形图很简单，不像普通的MP3文件那种很密密麻麻的波形数据图，这个问题帮忙支持下是算法问题么，有没有什么属性可以简单的区分此类波形图很简单的MP3文件，谢谢

**Comment by T-chuangxin** [comment]
你走一下断点，看看你传的那个MP3是不是CheapMP3中包含的那两种类型MP3，如果不是，你得再加！就比较麻烦了，你需要熟悉一下MP3的几种格式！如果时间紧的话，我的raw文件夹下有编译好的FFMpeg，使用的方式参照视频裁剪，用FFmpeg的命令行就OK了！

**Comment by PingStudyCode** [comment]
我打log看了下，基本不是mGlobalChannels = 1;就是mGlobalChannels = 2;然后今天再次实验的时候发现比特率为64的就会出现无法裁剪或则裁剪失败的情况，比特率为192时是OK的，这个裁剪工作是否与mp3音频文件的比特率有关系。

**Comment by T-chuangxin** [comment]
是的，比特率会影响MP3每帧的大小！帧大小计算错的话，裁剪就出错了！

**Comment by PingStudyCode** [comment]
能否告知目前这套算法支持哪些比特率，如果不支持64比特率，我能否读取MP3文件的比特率，然后针对比特率为64时不进行裁剪或者重新解析使用新的帧计算算法。

**Comment by T-chuangxin** [comment]
建议您先了解一下MP3格式

**Comment by PingStudyCode** [comment]
试了下本地的一些mp3文件，当比特率为128、192、320、319、318时可以正常剪切，当为99、119、118、113、116等值时无法正常剪切，我理解标准mp3比特率就是128/192/320这一类的，不明白为何会有319 318一类的，大神是否对这块有了解，谢谢。
另我看了这篇博文：http://blog.csdn.net/fulinwsuafcie/article/details/8972346
加上前面您说的，我理解mp3剪切目前不能适应所有的mp3文件，因为比特率不同帧长度也就不同，然后截取时也就会有差异，目前算法适用于标准比特率的文件，非标准的就会出现截取不正确的情况，是这样么？

**Comment by T-chuangxin** [comment]
大概是这个样子！其实只是没有解析出来，你最好再用FFMpeg命令裁剪一下试试！
